#!/usr/bin/env python
"""Run the public questions through Atlas.answer() and write stage1_public.json.

    python scripts/run_public_questions.py --data hackathon-data [--questions starter/public_questions.json]

The question file is the RECONSTRUCTED set (only the examples documented in the
Problem 1 specification); answers are produced by the implementation, never typed.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def run(data_dir: str, questions_path: str, out: str = "stage1_public.json", cut: int | None = None) -> dict:
    from stage1.atlas import Atlas, StudyGraph
    from starter.schemas import Question

    with open(questions_path, encoding="utf-8") as fh:
        qdoc = json.load(fh)
    raw_questions = qdoc["questions"] if isinstance(qdoc, dict) else qdoc

    graph = StudyGraph(str(data_dir))
    t0 = time.perf_counter()
    stats = graph.build(cut=cut)
    build_ms = (time.perf_counter() - t0) * 1000
    atlas = Atlas(graph)

    answers, timing = [], []
    for q in raw_questions:
        question = Question.model_validate({k: v for k, v in q.items() if k in Question.model_fields})
        t1 = time.perf_counter()
        ans = atlas.answer(question)
        ms = (time.perf_counter() - t1) * 1000
        answers.append(ans.model_dump())
        timing.append({"question_id": question.question_id, "ms": round(ms, 1)})

    result = {
        "reconstructed_starter": True,
        "note": "Answers generated by stage1.atlas against the RECONSTRUCTED public question set; not the organiser's file.",
        "data_dir": Path(data_dir).name,
        "cut": stats.get("cut"),
        "protocol_version": stats.get("protocol_version"),
        "build_ms": round(build_ms, 1),
        "answers": answers,
        "timing": timing,
    }
    with open(out, "w", encoding="utf-8") as fh:
        json.dump(result, fh, indent=2, default=str)
    return result


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data", default="hackathon-data")
    ap.add_argument("--questions", default=str(ROOT / "starter" / "public_questions.json"))
    ap.add_argument("--out", default="stage1_public.json")
    ap.add_argument("--cut", type=int, default=None)
    args = ap.parse_args()
    res = run(args.data, args.questions, args.out, args.cut)
    for a, t in zip(res["answers"], res["timing"]):
        ans = a["answer"]
        summary = f"list[{len(ans)}]" if isinstance(ans, list) else ans
        print(f"{a['question_id']:<18} {t['ms']:>8.1f} ms  conf={a['confidence']:.2f}  answer={summary}  evidence={len(a['evidence'])}")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
